### ISSUE TITLE
Bug in UpdateHistory

### ISSUE THREAD

**Issue by tlewis17** [Ackis/Professor#2]
The artifact history doesn't update. Shows an error is the IsQuestFlaggedCompleted() function on line 121. According to a subreddit discussion the IsQuestFlaggedCompleted() was deprecated in 8.2.5 and so it no longer works in 9.0.1. 

Changing it to C_QuestLog.IsQuestFlaggedCompleted() works:
new line 121: 
```
self.artifacts[icon].pristineSolved = C_QuestLog.IsQuestFlaggedCompleted(self.artifacts[icon].pristineId);
```

Tested and verified. 

Discussion:
https://www.reddit.com/r/wow/comments/jbcwhv/command_isquestflaggedcompleted_returning_error/

**Comment by Ackis** [comment]
Pushed.
